version: '3.2'
services:
  react-ui:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
       - "./:/app"
       - "/app/node_modules"

       